name: Build 👷

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deployment:
    strategy:
      matrix:
        arch: [amd64, arm64]
    name: Build the image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: matrix.arch == 'arm64'
        with:
          platforms: linux/arm64

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.arch }}
          load: true
          push: false
          tags: ${{ env.IMAGE_NAME }}

      - name: Test if AWS CLI works
        run: |
          docker run --rm ${{ env.IMAGE_NAME }} sh -c "/aws-cli-bin/aws --version"
