name: Build 👷

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@main

      - name: Extract AWS CLI version from Dockerfile
        run: echo "AWS_CLI_VERSION=$(grep -oP '(?<=ARG AWS_CLI_VERSION=)[^ ]+' Dockerfile)" >> $GITHUB_ENV
      
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
  
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          labels: |
              org.opencontainers.image.version=${{ env.AWS_CLI_VERSION }}
          tags: |
              ghcr.io/${{ github.repository }}:latest
              ghcr.io/${{ github.repository }}:${{ env.AWS_CLI_VERSION }}
          platforms: linux/amd64
          file: Dockerfile
          context: .
